config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations',sessions: 'users/sessions' }
  root "top#index"
    resources :posts, only: [:index ,:create, :new]
    resources :comments, only: [:create, :new, :edit, :show, :update]
    resources :users, only: [:new,:create,:show, :edit, :update]do
      member do
        delete 'destroy_all'
      end
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  validates :textBox1comment, :textBox2comment, :textBox3comment, :textBox4comment, :textBox5comment, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts
         has_many :comments
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  def after_sign_in_path_for(resource)
    posts_path
  end

private
    def sign_in_required
        redirect_to new_user_session_url unless user_signed_in?
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password,:password_confirmation, :image])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password,:password_confirmation, :image])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end
  def create
    Comment.create(comment_params)
  end
  def edit
    @comments = Comment.find(params[:id])
  end

  def show
    @comments = Comment.find(params[:id])
  end
  def update
    @comments = Comment.find(params[:id])
    @comments.update(comment_params)
  end

  def comment_show1
    return @comments.find(1)
  end
  private
  def comment_params
    params.require(:comment).permit(:textBox1comment, :textBox2comment, :textBox3comment, :textBox4comment, :textBox5comment).merge(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :sign_in_required, only: [:index]
  
  def index
  end

  def new
    @post = Post.new
  end

  def create  
    Post.create(post_params)
  end

  private
  def post_params
    params.require(:post).permit(:textBox1, :textBox2, :textBox3, :textBox4, :textBox5).merge(user_id: current_user.id)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  
  

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_sign_up_path_for(resource)
    new_comment_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post = @user.posts
    hash1 = @post.select(:textBox1).sum(:textBox1)
    hash2 = @post.select(:textBox2).sum(:textBox2)
    hash3 = @post.select(:textBox3).sum(:textBox3)
    hash4 = @post.select(:textBox4).sum(:textBox4)
    hash5 = @post.select(:textBox5).sum(:textBox5)
   @chart = {やることその1: hash1,やることその２: hash2,やることその３: hash3,やることその４: hash4,やることその５: hash5}
    
  end
  
  def destroy_all
    @user = User.find(params[:id])
    @post = @user.posts
    @post.destroy_all
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/create.html.haml
%canvas{id:"canvas"}
  %script{src:"/assets/background.js"}
.contents_success
  .success
    %h3 送信が完了しました。
    %a{class:"btn", href:"/posts"}
      メニューへ戻る

app/views/comments/edit.html.haml
%canvas{id:"canvas"}
  %script{src:"/assets/background.js"}
.contents__text
  .text
    = form_with(model: @comments, local: true) do |form|
      %h3
        やることリスト
      %label{class:"checkBox1comment"} 
        やることその１
        = form.text_field :textBox1comment, autofocus: true
      %label{class:"checkBox2comment"} 
        やることその2
        = form.text_field :textBox2comment
      %label{class:"checkBox3comment"} 
        やることその3
        = form.text_field :textBox3comment
      %label{class:"checkBox4comment"} 
        やることその4
        = form.text_field :textBox4comment
      %label{class:"checkBox5comment"} 
        やることその5
        = form.text_field :textBox5comment
      .send
        = form.submit "更新"

app/views/comments/new.html.haml
%canvas{id:"canvas"}
  %script{src:"/assets/background.js"}
.contents__text
  .text
    = form_with(model: @comment, local: true) do |form|
      %h3
        やることリスト
      %label{class:"checkBox1comment"} 
        やることその１
        = form.text_field :textBox1comment, autofocus: true
      %label{class:"checkBox2comment"} 
        やることその2
        = form.text_field :textBox2comment
      %label{class:"checkBox3comment"} 
        やることその3
        = form.text_field :textBox3comment
      %label{class:"checkBox4comment"} 
        やることその4
        = form.text_field :textBox4comment
      %label{class:"checkBox5comment"} 
        やることその5
        = form.text_field :textBox5comment
      .send
        = form.submit "送信"

app/views/comments/show.html.haml
.contents__background--image
  .contents__text--show
    .contents__text--show--form
      = form_with(url: new_post_path, method: :get ,local: true) do |form|
        %h3
          やることリスト
        %label{class:"checkBox1comment"} 
          やることその1 :
          = @comments.textBox1comment
        %label{class:"checkBox2comment"} 
          やることその2 :
          = @comments.textBox2comment
        %label{class:"checkBox3comment"} 
          やることその3 :
          = @comments.textBox3comment
        %label{class:"checkBox4comment"} 
          やることその4 :
          = @comments.textBox4comment
        %label{class:"checkBox5comment"} 
          やることその5 :
          = @comments.textBox5comment
        .send
          = form.submit "チェックする"
  = render "top/footer"

app/views/comments/update.html.haml
.contents--row
  .success
    %h3
      更新が完了しました。
    %a.btn{:href => "/posts"} 投稿一覧へ戻る
  %canvas{id:"canvas"}
%script{src:"/assets/background.js"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SeniorToDo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
    

app/views/posts/create.html.haml
.contents_success--background
  .contents_success
    .success
      %h3 送信が完了しました。
      %h4 今日、チェックリスト全てクリアの人は、
      %br  おめでとうございます！！
      %h4 今日、チェックリストあまり達成できなかった人は、
      %br  頑張りましょう！！
      %a{class:"btn", href:"/posts"}
        メニューへ戻る

app/views/posts/index.html.haml
%canvas{id:"canvas"}
  %script{src:"/assets/background.js"}
.wrapper
  = render "top/header"
  .main_user_index
    .main_user_index-btns
      %a{href: user_path(current_user),class:"reset button-shadow"}
        記録をみる
      %a{href:comment_path(current_user),class:"reset button-shadow"}
        チェックする
  = render "top/footer"
%script
  $(".menu-toggle").on('click', function() {
  $(this).toggleClass("on");
  $('.menu-section').toggleClass("on");
  $("nav ul").toggleClass('hidden');
  });

app/views/posts/new.html.haml
%canvas{id:"canvas"}
  %script{src:"/assets/background.js"}
.contents_row
  .container
    = form_with(model: [@post], local: true) do |form|
      %h3
        チェックする
      %label{class:"checkBox1",checked_value:"1", unchecked_value:"0"} 
        = form.check_box :textBox1
        やることその1
      %label{class:"checkBox2",checked_value:"1", unchecked_value:"0"}
        = form.check_box :textBox2
        やることその２
      %label{class:"checkBox3",checked_value:"1", unchecked_value:"0"}
        = form.check_box :textBox3
        やることその３
      %label{class:"checkBox4",checked_value:"1", unchecked_value:"0"}
        = form.check_box :textBox4
        やることその４
      %label{class:"checkBox5",checked_value:"1", unchecked_value:"0"}
        =form.check_box :textBox5
        やることその５
      .send
        = form.submit "送信"

app/views/top/_footer.html.haml
.footer
  .footer-logo
    =link_to "Senior-to-do 2020", root_path

app/views/top/_header.html.haml
.header
  .header_title
    = link_to root_path do
      %img{src:"/assets/Senior-to-do-title.png"}
  - if user_signed_in?
    .header_user-name
      = link_to edit_user_registration_path do
        = current_user.name
      .reset_btn
        = link_to posts_path do
          チェック
      .header__icon
        = link_to edit_comment_path(current_user) do
          設定
  -else
    .header_log-in
      = link_to "ログイン", new_user_session_path, class:"log-in_btn"
    .header_sign-in
      = link_to "新規登録", new_user_registration_path, class: "sign-in_btn"
.header_min
  .header_title
    = link_to root_path do
      %img{src:"/assets/Senior-to-do-title.png"}
  .menu-section
    .menu-toggle
      .one
      .two
      .three
      %nav
        %ul{role:"navigation", class:"hidden"}
          - if user_signed_in?
            %li{class:"header_user-name"}
              = link_to edit_user_registration_path do
                = current_user.name
            %li{class:"reset_btn"}
              = link_to "チェック", posts_path
            %li{class:"reset_btn"}
              = link_to "設定", edit_comment_path(current_user)
          -else
            %li
              %a{href: new_user_session_path} ログイン
            %li
              %a{href:new_user_registration_path} 新規登録

app/views/top/index.html.haml
.wrapper
  = render "header"
  .main
    .main_text
      Check what you did today!
      %h6 今日やったことをチェックしよう！
    %video{src:"/assets/mixkit-sun-rays-pass-through-the-clouds-in-the-mountains-4113.mp4",autoplay:"autoplay", loop:"loop", muted: "muted"}
  = render "footer"
%script
  $(".menu-toggle").on('click', function() {
  $(this).toggleClass("on");
  $('.menu-section').toggleClass("on");
  $("nav ul").toggleClass('hidden');
  });

app/views/users/destroy_all.html.haml
.contents--row
  .success
    %h3
      削除が完了しました。
    %a.btn{href: posts_path} 投稿一覧へ戻る
  %canvas{id:"canvas"}
%script{src:"/assets/background.js"}

app/views/users/show.html.haml
%canvas{id:"canvas"}
  %script{src:"/assets/background.js"}
.wrapper
  = render "top/header"
  .data_show
    %h1 達成した記録
    = column_chart @chart ,xtitle: "質問", ytitle: "成功数", label: "成功数"
  .delete_data_btn
    = link_to '全ての記録したデータを削除',destroy_all_user_path, method: :delete, id:"button", data: {confirm: "全て記録したデータを削除しますか？"} 
  = render "top/footer"
%script
  $(".menu-toggle").on('click', function() {
  $(this).toggleClass("on");
  $('.menu-section').toggleClass("on");
  $("nav ul").toggleClass('hidden');
  });